
CREATE TABLE [dbo].[Applications](
	[Name] [NVARCHAR](40) NOT NULL,
	[Description] [NVARCHAR](100) NULL,
	[IsActive] [BIT] NOT NULL,
 CONSTRAINT [PK_Application] PRIMARY KEY CLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Applications] ADD  CONSTRAINT [DF_Application_Active]  DEFAULT ((1)) FOR [IsActive]
GO