@endpoint=https://localhost:7295/
@version=v1

### get DefectPieceRefs

GET {{endpoint}}{{version}}/DefectPieceRefs
Content-Type: application/json

### get DefectPieceRefs by KeyField

GET {{endpoint}}{{version}}/DefectPieceRefs/TST
Content-Type: application/json

### post DefectPieceRefs

POST {{endpoint}}{{version}}/DefectPieceRefs
Content-Type: application/json


                {
                    "PieceRef": "PieceRef1",
                    "OnBody": true,
                    "OnCap": false,
                    "English_Desc": "Level 1",
                    "Defect_Desc": "defect 1",
                    "ReadOnly": true,
                    "isActive": true
             }
### put DefectPieceRefs

PUT {{endpoint}}{{version}}/DefectPieceRefs
Content-Type: application/json


                {
                    "PieceRef": "PieceRef1",
                    "OnBody": true,
                    "OnCap": false,
                    "English_Desc": "Level 1",
                    "Defect_Desc": "defect 1",
                    "ReadOnly": true,
                    "isActive": true
             }
### delete DefectPieceRefs

DELETE {{endpoint}}{{version}}/DefectPieceRefs/TST
Content-Type: application/json

