@endpoint=https://localhost:7295/
@version=v1

### get Languages

GET {{endpoint}}{{version}}/Languages
Content-Type: application/json

### get Languages by KeyField

GET {{endpoint}}{{version}}/Languages/GERMAN
Content-Type: application/json

### post Languages

POST {{endpoint}}{{version}}/Languages
Content-Type: application/json


                {
                    "name": "GERMAN",
                    "isActive": true
                }
### put Languages

PUT {{endpoint}}{{version}}/Languages
Content-Type: application/json


                {
                    "name": "GERMAN",
                    "isActive": true
                }
### delete Languages

DELETE {{endpoint}}{{version}}/Languages/GERMAN
Content-Type: application/json

