@endpoint=https://localhost:7295/
@version=v1

### get TranslationTypes

GET {{endpoint}}{{version}}/TranslationTypes
Content-Type: application/json

### get TranslationTypes by KeyField

GET {{endpoint}}{{version}}/TranslationTypes/T1
Content-Type: application/json

### post TranslationTypes

POST {{endpoint}}{{version}}/TranslationTypes
Content-Type: application/json


        {
            "translation_type": "T1",
            "description": "TestTranslationType",
            "isActive": true
        }
### put TranslationTypes

PUT {{endpoint}}{{version}}/TranslationTypes
Content-Type: application/json


        {
            "translation_type": "T1",
            "description": "TestTranslationType",
            "isActive": true
        }
### delete TranslationTypes

DELETE {{endpoint}}{{version}}/TranslationTypes/T1
Content-Type: application/json

